project:
  type: book
  output-dir: docs

book:
  title: "Practical Guide to Health Data Science in Aotearoa New Zealand"
  author: "Precision Driven Health"
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, linkedin]
  cover-image: /img/cover.jpg
  date: 12/01/2022
  date-format: "MMMM YYYY"
  chapters:
    - 00-welcome.qmd
    - 01-intro.qmd
    - 02-starting.qmd
    - 03-basics.qmd
    - 04-collaboration.qmd
    - 05-data-landscape.qmd
    - 06-data-identifiability.qmd
    - 07-data-preparation.qmd
    - 08-modelling.qmd
    - 09-evaluation.qmd
    - 10-deployment-lifecycle.qmd
    - references.qmd
  # comments:
  #   hypothesis: true

# banner style for the title
# title-block-banner: "#008084"
# it's really large - unsure I like it

# table of contents settings
toc-location: right
toc-title: "On this page"

# captions and references
reference-location: section
cap-location: margin
bibliography: references.bib
citations-hover: true
citation-location: margin
footnotes-hover: true

# external links
link-external-icon: true
link-external-newwindow: true

format:
  html:
    theme: cosmo

execute:
  freeze: auto