project:
  type: book
  output-dir: docs

book:
  title: "Health Data Science in Aotearoa New Zealand: A Practical Guide"
  author: "Precision Driven Health"
  search: true
  sharing: [twitter, linkedin]
  cover-image: /img/cover.jpg
  date: 17 November 2022
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-starting.qmd
    - 03-basics.qmd
    - 04-collaboration.qmd
    - 05-data-landscape.qmd
    - 06-data-access.qmd
    - 07-data-identifiability.qmd
    - 08-data-preparation.qmd
    - 09-modelling.qmd
    - 10-evaluation.qmd
    - 11-deployment-lifecycle.qmd
    - 12-references.qmd
    - 13-glossary.qmd
  # comments:
  #   hypothesis: true

# banner style for the title
# title-block-banner: "#008084"
# it's really large - unsure I like it

# table of contents settings
toc-location: right
toc-title: "On this page"

# captions and references
reference-location: section
cap-location: margin
bibliography: references.bib
csl: csl/archiv-fur-geschichte-der-philosophie.csl
citations-hover: true
citation-location: margin
footnotes-hover: true
# nocite: |
#   @*

# external links
link-external-icon: true
link-external-newwindow: true

format:
  html:
    theme: cosmo

execute:
  freeze: auto